### ISSUE TITLE
Feature request: vim j/k mode

### ISSUE THREAD

**Issue by canadaduane** [alexilyaev/runrun-cli#34]
Could there be an option to enable "vim" style key bindings, just for up and down movement?

I'm imagining an option such as `rr --vim` that would disable completion and enable "j" for down and "k" for up. I would then probably alias this on my machine, e.g. `alias rr="rr --vim"`.

**Comment by alexilyaev** [comment]
@canadaduane Unfortunately the mechanism of navigating the list is controlled by `prompts` and we don't have a way to adjust it from our code 😔

I see they have a similar open issue on their repo:
https://github.com/terkelg/prompts/issues/352

Although it is more complicated with an `autocomplete` mode (which is what we use).
I suggest to pitch in on that issue.

Closing for now, feel free to report again if the feature will be added in `prompts` in the future 🙏🏼

**Comment by canadaduane** [comment]
It looks like they allow "j/k" keys to move up/down if the prompt is a "select":

https://github.com/terkelg/prompts/blob/master/lib/util/action.js#L14

**Comment by alexilyaev** [comment]
Published in version https://github.com/alexilyaev/runrun-cli/releases/tag/v2.0.0
