### ISSUE TITLE
Add ability to run the last command quickly

### ISSUE THREAD

**Issue by adamkleingit** [alexilyaev/runrun-cli#8]
When you run a command regularly, you can see it in shell history, as well as search back to it with ctrl+r or using the arrow keys.

It would be nice to somehow add the selected command to shell history, if it's possible

**Comment by alexilyaev** [comment]
Can you share a flow of events where this is useful?
As it takes time to find a command in history, perhaps it's just as easy to run `runrun` to execute what you want.

One thing I can think of is running an npm script with extra arguments (not yet supported).
That would be useful in command history.

@elektronik2k5 mentioned [npm-quick-run](https://github.com/bahmutov/npm-quick-run), which has a way to run scripts with few characters, but the interactive mode won't add to command history either (I think).

**Comment by alexilyaev** [comment]
After using `runrun` for a while, I've started experiencing what you were talking about...
Running a script like `lint:eslint` through `runrun` and then wanting to run it again by pressing the Up arrow key.

So... if it's possible, should definitely push the command to the command line history.

**Comment by adamkleingit** [comment]
On the other hand if you want to press up to get to runrun again, it will be annoying that it's not in the user history.
So I guess implementing your own history inside runrun sounds like the best solution to me.

**Comment by alexilyaev** [comment]
@zoharyzgiaev Let's move forward with this...

Similar to this package:
https://github.com/ruyadorno/lru-cache-fs/blob/master/index.js

We don't need lru-cache, let's just save files with latest used script name.
For each CWD we'll have a file with just a string (e.g. 'lint-eslint').

Let's add [fs-extra ](https://github.com/jprichardson/node-fs-extra) and make sure to use [env-paths](https://github.com/sindresorhus/env-paths).

**Comment by alexilyaev** [comment]
@adamkleingit Good news, it's live! 😎.
Done in https://github.com/alexilyaev/runrun-cli/pull/13

Read the [v1.2.0 Release Notes](https://github.com/alexilyaev/runrun-cli/releases/tag/v1.2.0)
